### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mervick** [matthiasbock/python-altium#1]

**Comment by justinmassiot** [comment]
Hey @mervick ,
In my opinion you'd better look at the [source project](https://github.com/vadmium/python-altium), where there **is** a license defined.

**Comment by matthiasbock** [comment]
Hi @mervick,
Thanks for the hint. I will add a license, as soon as I have decided for one.
Is there a special reason for asking?
Cheers, Matthias

**Comment by mervick** [comment]
I want to use this sources in commercial project. Without license it's not possible. 
The original project has WTFPL license and does not apply to forks.
For my needs would be good LGPL or MIT, such licenses are most often used in open source.

**Comment by mervick** [comment]
From GitHub help page:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

**Comment by matthiasbock** [comment]
I agree, the license of what you call the "original project" does not apply to this repo. I am currently deciding but am tending towards using AGPL since in general I am okay with commercial use but only as long as the resulting source code is made public again. I am not paid for this work, so I consider the publication of derivative code as my "payment".

**Comment by matthiasbock** [comment]
License file added with commit ef0f14c
